"""Added Allocation table with room number

Revision ID: 07de44398fa6
Revises: 0c01c9a8045d
Create Date: 2026-03-19 11:55:08.946239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07de44398fa6'
down_revision = '0c01c9a8045d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('residence_id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('allocated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['residence_id'], ['housing_listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocation')
    # ### end Alembic commands ###
