"""initial migration with housing

Revision ID: 0c01c9a8045d
Revises: 7aaf21991dfe
Create Date: 2026-03-19 00:59:17.401002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c01c9a8045d'
down_revision = '7aaf21991dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housing_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('region', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('capacity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gender_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('image_file', sa.String(length=255), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('title')
        batch_op.drop_column('location')
        batch_op.drop_column('monthly_rent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('housing_listing', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_rent', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image_file')
        batch_op.drop_column('gender_type')
        batch_op.drop_column('capacity')
        batch_op.drop_column('address')
        batch_op.drop_column('region')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
