"""initial migration with admin fields

Revision ID: 7aaf21991dfe
Revises: 
Create Date: 2026-03-18 17:40:13.113847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaf21991dfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('available_rooms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=60), nullable=False),
    sa.Column('student_number', sa.String(length=8), nullable=True),
    sa.Column('student_id', sa.String(length=13), nullable=True),
    sa.Column('surname', sa.String(length=50), nullable=True),
    sa.Column('full_names', sa.String(length=100), nullable=True),
    sa.Column('cell_number', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('home_address', sa.String(length=200), nullable=True),
    sa.Column('province', sa.String(length=50), nullable=True),
    sa.Column('nok_name', sa.String(length=100), nullable=True),
    sa.Column('nok_relationship', sa.String(length=50), nullable=True),
    sa.Column('nok_cell', sa.String(length=10), nullable=True),
    sa.Column('campus', sa.String(length=50), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('level_of_study', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('application_status', sa.String(length=20), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('student_number'),
    sa.UniqueConstraint('username')
    )
    op.create_table('room_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_submitted', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['housing_listing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roommate_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cleanliness_level', sa.Integer(), nullable=True),
    sa.Column('noise_tolerance', sa.Integer(), nullable=True),
    sa.Column('sleep_schedule', sa.String(length=50), nullable=True),
    sa.Column('study_habits', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roommate_preferences')
    op.drop_table('room_application')
    op.drop_table('user')
    op.drop_table('housing_listing')
    # ### end Alembic commands ###
